[[rockset-output]]
=== Configure the Rockset output

++++
<titleabbrev>Rockset</titleabbrev>
++++

The Rockset output writes events in JSON format to a Rockset collection.

To use this output, edit the {beatname_uc} configuration file to disable the {es}
output by commenting it out, and enable the console output by adding `output.console`.

Example configuration:

[source,yaml]
------------------------------------------------------------------------------
output.rockset:
  apikey: ...
  apiserver: api.usw2a1.rockset.com
  workspace: commons
  collection: filebeat
------------------------------------------------------------------------------

ifdef::apm-server[]
[float]
==== Configure the {kib} output

include::../../../../shared-kibana-endpoint.asciidoc[tag=shared-kibana-config]
endif::[]

==== Configuration options

You can specify the following `output.console` options in the +{beatname_lc}.yml+ config file:

===== `enabled`

The enabled config is a boolean setting to enable or disable the output. If set
to false, the output is disabled.

The default value is `true`.

===== `pretty`

If `pretty` is set to true, events written to stdout will be nicely formatted. The default is false.

===== `codec`

Output codec configuration. If the `codec` section is missing, events will be json encoded using the `pretty` option.

See <<configuration-output-codec>> for more information.

===== `bulk_max_size`

The maximum number of events to buffer internally during publishing. The default is 2048.

Specifying a larger batch size may add some latency and buffering during publishing. However, for Console output, this
setting does not affect how events are published.

Setting `bulk_max_size` to values less than or equal to 0 disables the
splitting of batches. When splitting is disabled, the queue decides on the
number of events to be contained in a batch.
